services:
  - type: web
    name: tft-meta-analyzer-backend
    rootDir: backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    healthCheckPath: /api/health/ping