# Render 배포 설정
services:
  - type: web
    name: tft-meta-analyzer-backend
    runtime: node
    plan: free
    region: oregon # 또는 singapore (한국과 가까운 지역)
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    
    # 환경 변수 (민감한 정보는 Render Dashboard에서 설정)
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://your-frontend-domain.pages.dev
    
    # 자동 배포 설정
    branch: main
    autoDeploy: true
    
    # 리소스 설정
    disk:
      name: data
      sizeGB: 1
      mountPath: /data
    
    # 서비스 설정
    healthCheck:
      path: /api/health
      intervalSeconds: 30
      timeoutSeconds: 10
      unhealthyThresholdCount: 3
      healthyThresholdCount: 2
    
    # 로그 설정
    logging:
      level: info
      
    # 빌드 캐시 설정
    buildFilter:
      paths:
        - backend/**
        - shared/**
        - package.json
        - render.yaml